<?php
return [
    // Existing mappings from your second file
    'maadi' => 'المعادى',
    'el maadi' => 'المعادى',
    'al maadi' => 'المعادى',
    'zahra el maadi' => 'زهراء المعادى',
    'zahra al maadi' => 'زهراء المعادى',
    'maadi gardens' => 'حدائق المعادى',
    'maadi corniche' => 'كورنيش المعادى',
    'new maadi' => 'المعادى الجديدة',

    'nasr city' => 'مدينة نصر',
    'nasr' => 'مدينة نصر',
    'medinet nasr' => 'مدينة نصر',
    'zahra nasr city' => 'زهراء مدينة نصر',

    'new cairo' => 'القاهره الجديدة',
    'cairo' => 'القاهره الجديدة',

    'heliopolis' => 'مصر الجديدة',
    'misr el gedida' => 'مصر الجديدة',
    'masr el gedida' => 'مصر الجديدة',
    'korba' => 'مصر الجديدة',
    'new heliopolis' => 'هليوبليس الجديدة',

    'mohandessin' => 'المهندسين',
    'mohandeseen' => 'المهندسين',
    'engineers' => 'المهندسين',

    'zamalek' => 'الزمالك',
    'dokki' => 'الدقى',
    'agouza' => 'العجوزه',
    'agoza' => 'العجوزه',

    '6th of october' => '6 اكتوبر',
    '6 october' => '6 اكتوبر',
    'october' => '6 اكتوبر',
    'october gardens' => 'حدائق اكتوبر',
    'october 15 may' => '15 مايو',

    'sheikh zayed' => 'الشيخ زايد',
    'zayed' => 'الشيخ زايد',

    'fifth settlement' => 'التجمع الخامس',
    '5th settlement' => 'التجمع الخامس',
    'tagamoa' => 'التجمع الخامس',
    'first settlement' => 'التجمع الاول',
    '1st settlement' => 'التجمع الاول',
    'third settlement' => 'التجمع الثالث',
    '3rd settlement' => 'التجمع الثالث',

    'rehab' => 'الرحاب',
    'al rehab' => 'الرحاب',

    'shorouk' => 'الشروق',
    'el shorouk' => 'الشروق',

    'obour' => 'العبور',
    'el obour' => 'العبور',

    'haram' => 'الهرم',
    'el haram' => 'الهرم',
    'pyramid' => 'الهرم',
    'pyramid gardens' => 'حدائق الاهرام',
    'mariouteya haram' => 'مريوطية الهرم',

    'faisal' => 'فيصل',
    'mariouteya faisal' => 'مريوطيه فيصل',
    'faisal branch' => 'فرع فيصل',

    'helwan' => 'حلوان',
    'helwan gardens' => 'حدائق حلوان',

    'downtown' => 'وسط البلد',
    'tahrir' => 'التحرير',
    'manial' => 'المنيل',
    'el manial' => 'المنيل',
    'manial shiha' => 'منيل شيحا',

    'garden city' => 'جاردن سيتي',
    'old cairo' => 'مصر القديمة',
    'coptic cairo' => 'مصر القديمة',

    'shubra' => 'شبرا الخيمة',
    'shobra' => 'شبرا الخيمة',
    'shubra misr' => 'شبرا مصر',

    'ain shams' => 'عين شمس',
    'abbasia' => 'العباسية',
    'el abbasia' => 'العباسية',
    'abdin' => 'عابدين',

    'sayeda zeinab' => 'السيدة زينب',
    'sayeda aisha' => 'السيده عائشه',

    'rod el farag' => 'روض الفرج',
    'warraq' => 'الوراق',
    'el warraq' => 'الوراق',
    'warraq el arab' => 'وراق العرب',
    'warraq el hadar' => 'وراق الحضر',

    'imbaba' => 'امبابة',
    'kit kat' => 'كيتكات',
    'bulaq' => 'بولاق ابو العلا',
    'bulaq dakrour' => 'بولاق الدكرور',

    'ramses' => 'رمسيس',
    'ataba' => 'العتبة',
    'el ataba' => 'العتبة',

    'fagala' => 'الفجالة',
    'el fagala' => 'الفجالة',

    'basateen' => 'البساتين',
    'el basateen' => 'البساتين',

    'almaza' => 'الماظة',
    'el almaza' => 'الماظة',

    'airport' => 'المطار',
    'cairo airport' => 'المطار',
    'nozha airport' => 'مطار النزهه',
    'alexandria airport' => 'مطار الاسكندرية',

    'mokattam' => 'المقطم',
    'el mokattam' => 'المقطم',
    'muqattam' => 'المقطم',

    'madinaty' => 'مدينتى',
    'medicity' => 'مدينتى',

    'dreamland' => 'دريم لاند',
    'smart village' => 'القرية الذكية',

    'bdr city' => 'مدينة بدر',
    'badr city' => 'مدينة بدر',

    '15 may' => '15 مايو',

    'sheraton' => 'شيراتون',
    'nile corniche' => 'كورنيش النيل',

    'new nozha' => 'النزهة الجديدة',
    'middle plateau' => 'الهضبة الوسطى',
    'future city' => 'مدينة المستقبل',
    'the future' => 'المستقبل',
    'zawya hamra' => 'الزاوية الحمرا',

    'suez bridge' => 'جسر السويس',
    'autostrad' => 'الاتوستراد',
    'tura' => 'طره',
    'tura balad' => 'طرة البلد',

    'qoba gardens' => 'حدائق القبة',
    'qoba baths' => 'حمامات القبة',
    'saray qoba' => 'سراى القبة',
    'qoba bridge' => 'كوبرى القبة',

    'qasr el aini' => 'القصر العينى',
    'dar es salaam' => 'دار السلام',

    'helmeya zeytoun' => 'حلمية الزيتون',
    'ezbet el nakhl' => 'عزبة النخل',
    'zeytoun' => 'الزيتون',
    'zeytoun gardens' => 'حدائق الزيتون',

    'omraneya' => 'عمرانية',
    'el omraneya' => 'العمرانية',

    'zaher' => 'الضاهر',
    'el zaher' => 'الظاهر',

    'marg' => 'المرج',
    'new marg' => 'المرج الجديدة',

    'qotamia' => 'القطامية',
    'army square' => 'ميدان الجيش',
    'wayli' => 'الوايلى',
    'ramaya' => 'الرمايه',

    'safaga' => 'سفاجا',
    'abud' => 'عبود',
    'matareya' => 'المطرية',
    'qadisiya' => 'القادسية',
    'moneeb' => 'المنيب',
    'sabtiya' => 'السبتية',
    'talibiya' => 'الطالبية',
    'salah salem' => 'صلاح سالم',
    'mariouteya' => 'المريوطية',

    'damieta' => 'دمياط',
    'new damietta' => 'دمياط الجديدة',

    'golf land' => 'ارض الجولف',
    'abu zabal' => 'ابو زعبل',
    'lewaa land' => 'ارض اللواء',

    'mousky' => 'الموسكى',
    'bab el shaaria' => 'باب الشعرية',
    'demerdash' => 'الدمرداش',
    'amiriya' => 'الاميرية',
    'salam' => 'السلام',
    'namous bridge' => 'كوبري الناموس',
    'beshtil' => 'بشتيل',
    'hasania' => 'الحسانية',
    'qalaj' => 'القلج',
    'sharabiya' => 'الشرابية',

    'mansoura' => 'المنصورة',
    'mansoura branch' => 'فرع المنصورة',
    'mansouriya' => 'المنصوريه',

    'tanta' => 'طنطا',
    'mahalla' => 'المحله',
    'mostrod' => 'مسطرد',
    'metro' => 'مترو',
    'mozallat' => 'المظلات',
    'manshiet nasser' => 'منشية ناصر',
    'derasa' => 'الدراسة',
    'craftsmen' => 'الحرفيين',

    'ismailia' => 'الاسماعيلية',
    'fustat gedida' => 'الفسطاط الجديده',
    'helmeya housing' => 'مساكن الحلمية',
    'wadi houf' => 'وادى حوف',
    'basos' => 'باسوس',

    'menoufia' => 'المنوفية',
    'kafr el sheikh' => 'كفر الشيخ',
    'bab el louk' => 'باب اللوق',
    'ring road' => 'الطريق الدائرى',
    'cairo university' => 'جامعة القاهرة',
    'qanater' => 'القناطر',
    'manshiet qanater' => 'منشأة القناطر',

    'shibin el kom' => 'شبين الكوم',
    '10th of ramadan' => 'العاشر من رمضان',
    'saft el laban' => 'صفط اللبن',
    'manshiet el sadr' => 'منشية الصدر',

    'sharqiya' => 'الشرقية',
    'mit ghamr' => 'ميت غمر',
    'dakahlia' => 'الدقهلية',
    'el tel' => 'التل',

    'sohag' => 'سوهاج',
    'industrial zone' => 'المنطقة الصناعية',
    'assiut' => 'اسيوط',
    'minya' => 'المنيا',
    'qalyoubia' => 'القليوبية',
    'aswan' => 'اسوان',

    'banha' => 'بنها',
    'fayed' => 'فايد',
    'fayoum' => 'الفيوم',
    'zagazig' => 'الزقازيق',
    'luxor' => 'الاقصر',
    'hurghada' => 'الغردقه',
    'damanhour' => 'دمنهور',
    'kafr el zayat' => 'كفر الزيات',
    'itai el baroud' => 'ايتاي البرود',
    'gharbia' => 'الغربيه',
    'kafr el dawwar' => 'كفر الدوار',
    'sadat city' => 'مدينة السادات',
    'hawamdeya' => 'الحوامديه',
    'marsa matrouh' => 'مرسي مطروح',
    'behera' => 'البحيرة',

    'borg el arab' => 'برج العرب',
    'smoha' => 'سموحه',
    'semanoud' => 'سمنود',
    'qalyub' => 'قليوب',
    'thousand housing branch' => 'فرع الف مسكن',
    'bani suef' => 'بني سويف',
    'qantara' => 'القنطرة',
    'qena' => 'قنا',
    'sharm el sheikh' => 'شرم الشيخ',
    'shabrament' => 'شبرامنت',
    'new valley' => 'الوادي الجديد',
    'minya el qamh' => 'منيا القمح',
    'kerdasa' => 'كرداسه',
    'yellow mountain' => 'الجبل الأصفر',
    'oases road 6 october' => 'طريق الواحات 6 اكتوبر',
    'badrashin' => 'البدرشين',
    'marsa alam' => 'مرسي علم',
    'girga' => 'جرجا',
    'saff' => 'الصف',
    'ausim' => 'اوسيم',
    'new helmeya' => 'الحلميه الجديده',
    'red derby' => 'الدرب الاحمر',
    'mit halfa' => 'ميت حلفا',
    'mit nama' => 'ميت نما',
    'citadel' => 'القلعه',
    'doueiqa' => 'الدويقه',
    'imam shafei' => 'الامام الشافعى',
    'bahtim' => 'بهتيم',
    'khosous' => 'الخصوص',
    'khanka' => 'الخانكه',
    'ain sokhna' => 'العين السخنه',
    'maspero' => 'ماسبيرو',
    'gamaleya' => 'الجمالية',
    'nobaria' => 'النوبارية',
    'cairo alexandria desert road' => 'طريق مصر اسكندرية الصحراوى',
    'giza square' => 'ميدان الجيزة',
    'motamadiya' => 'المعتمدية',
    'tur sinai' => 'طور سيناء',
    'abu rawash' => 'ابو رواش',
    'atfih' => 'اطفيح',
    'new giza' => 'new giza',
    'sea el azam giza' => 'البحر الاعظم جيزة',
    'ayat' => 'العياط',
    'baragil' => 'البراجيل',
    'abu el nomros' => 'ابو النمرس',
    'malik saleh' => 'الملك الصالح',
    'new administrative capital' => 'العاصمة الادارية',
    'wadi natrun' => 'وادى الناطرون',
    'tebin' => 'التبين',

    // Alexandria cities
    'alexandria' => 'الاسكندرية',
    'alex' => 'الاسكندرية',
    'agamy' => 'العجمي',
    'wardian alexandria' => 'الورديان اسكندرية',
    'hannoville' => 'الهانوفيل',
    'bitash' => 'البيطاش',
    'qabbary alexandria' => 'القبارى اسكندرية',
    'dekheila alexandria' => 'الدخيلة اسكندرية',
    'marina' => 'مارينا',
    'dahshour' => 'دهشور',
    'saqqara' => 'سقارة',
    'amreya' => 'العاميرية',
    'mina el basal' => 'مينا البصل',
    'dekheila' => 'الدخيلة',
    'abu youssef' => 'ابو يوسف',
    'shatby' => 'الشاطبي',
    'sheds' => 'شدس',
    'victoria' => 'فيكتوريا',
    'zizinia' => 'زيزينيا',
    'sidi beshr' => 'سيدي بشر',
    'miami' => 'ميامي',
    'tharwat' => 'ثروت',
    'fleming' => 'فلمنج',
    'awayed' => 'العوايد',
    'laurent' => 'لوران',
    'cleopatra' => 'كليوباترا',
    'mohamed naguib' => 'محمد نجيب',
    'mostafa kamel' => 'مصطفي كامل',
    'manshia' => 'المنشيه',
    'gianaclis' => 'جناكليس',
    'bookly' => 'بوكلي',
    'sayouf' => 'السيوف',
    'asafra' => 'العصافره',
    'ibrahimiya' => 'الابراهيميه',
    'hadra' => 'الحضره',
    'mandara' => 'المندره',
    'bakos' => 'باكوس',
    'wezara' => 'الوزاره',
    'roshdy' => 'رشدي',
    'mohamed mahfouz' => 'محمد محفوظ',
    'khalil hamada' => 'خليل حماده',
    'winget' => 'ونجت',
    'ibrahimiya' => 'ابراهيميه',
    'camp caesar' => 'كامبشيزار',
    'university' => 'الجامعه',
    'gabriel' => 'غبريال',
    'zizenia' => 'زيزنيا',
    'saraya' => 'السرايا',
    'kafr abdo' => 'كفر عبده',
    'ezbet saad' => 'عزبة سعد',
    'kom el shoqafa' => 'كوم الشقافه',
    'water pump' => 'وابور المياة',
    'saba pasha' => 'سابا باشا',
    'gleem' => 'جليم',
    'sporting' => 'سبورتنج',
    'sultan hussein' => 'السلطان حسين',
    'san stefano' => 'سان ستيفانو',
    'new miami' => 'ميامي الجديدة',
    'shallalat' => 'الشلالات',
    'sidi gaber' => 'سيدى جابر',
    'raml station' => 'محطه الرمل',
    'laban' => 'اللبان',
    'saa' => 'الساعة',
    'azarita' => 'الازاريطة',
    'ras el soda' => 'الراس السودا',
    'falaky' => 'الفلكي',
    'stanley' => 'ستانلي',
    'moharam bek' => 'محرم بيك',
    'nakheel' => 'النخيل',
    'abou qir' => 'ابو قير',
    'qabbary' => 'القباري',
    'alexandria station' => 'موقف اسكندريه',
    'montaza' => 'المنتزة',
    'maamora' => 'المعموره',
    'bahary' => 'بحري',
    'wardian' => 'الورديان',
    'gheit el enab' => 'غيط العنب',
    'karmouz' => 'كرموز',
    'kom el dekka' => 'كوم الدكه',
    'downtown' => 'داون تاون',
    'misr station' => 'محطه مصر',
    'tawson' => 'طوسون',
    'attarine' => 'العطارين',
    'kilo 21' => 'الكيلو 21',
    'abees' => 'ابيس',
    'ameriya' => 'العامريه',
    'king mariout' => 'كينج مريوط',

    'el gouna' => 'الجونة',
    'fifth settlement branch' => 'فرع التجمع',
    'western oases' => 'الواحات البحرية',
    'manashi' => 'المناشي',
    'wardan menoufia' => 'وردان المنوفية',
    'nuweiba' => 'نويبع',
    'shibin qanater' => 'شبين القناطر',
    'qusseir' => 'القصير',
    'dahab' => 'دهب',
    'main branch' => 'الفرع الرئيسي',
    'port said' => 'بورسعيد',
    'suez' => 'السويس',
    'ras el bar' => 'راس البر',
    'port fuad' => 'بورفؤاد',
    'ras sudr' => 'راس سدر',
    'flyer' => 'فلاير',
    'ras ghareb' => 'راس غارب',
    'haroun branch' => 'فرع هارون',
    'galatma' => 'الجلاتمه',

    // Additional mappings for locations that might have English equivalents
    'ghamra' => 'غمرة',
    'north coast' => 'الساحل الشمالى',
    'new alamein' => 'العلمين الجديدة',
    'red sea' => 'البحر الاحمر',
    'north sinai' => 'شمال سيناء',
    'south sinai' => 'جنوب سيناء',
    'el arish' => 'العريش'
];
